# Generated by Django 3.2.8 on 2021-10-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chp',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pic',
            name='id',
        ),
        migrations.AlterField(
            model_name='chp',
            name='cid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pic',
            name='pid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
